Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

Rails/LexicallyScopedActionFilter:
  Enabled: false
  Include:
    - 'app/controllers/sessions_controller.rb'

RSpec/NestedGroups:
  Max: 4